services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html:cached
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
